name: Quality and Tests

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  qa:
    runs-on: ubuntu-latest
    name: Quality Analysis
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black==23.3.0 pylint==2.17.1
    - name: Black formatting
      run: black .
    - name: Pylint
      run: pylint ./src
    - name: Pytest
      run: |
        PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/unit
        PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/functional
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pytest
      run: |
        PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/unit
        PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/functional
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: output/test/code-coverage.html